mysql > INSERT;
INTO;
roles;
VALUES(1, 'user', now(), now());
mysql > INSERT;
INTO;
roles;
VALUES(2, 'moderator', now(), now());
mysql > INSERT;
INTO;
roles;
VALUES(3, 'admin', now(), now());
